%token COMMENT SUM SUB MULT DIV MOD INCR DECR GREATER SMALLER
%token GREATER_EQUAL SMALLER_EQUAL EQUAL DIFF ASSIGNMENT AND OR NOT
%token OPEN_PAR CLOSE_PAR OPEN_BRACKET CLOSE_BRACKET SEMI_COLLON
%token QUOTE WHILE FOR IF ELSE BREAK CONTINUE RETURN SWITCH CASE
%token DEFAULT FLOAT INT CHAR VOID STRING_LITERALL CONSTANT


